### ISSUE TITLE
机构ID包含&nbsp;时，在该机构ID下创建用户会报错

### ISSUE THREAD

**Issue by zhmouohz** [lirenhao/BasicDemo#1]
机构ID包含&nbsp;时，在该机构ID下创建用户会报错
例如：机构id为&nbsp;00% ，访问http://localhost:8000/api/permit/user?org_id=&nbsp;00% 会报错
机构id为&nbsp;00，在其机构下创建用户则无法显示

------------------------------------------
问题是由&号和%号造成的，目前没有发现其他特殊符号会造成问题

**Comment by lirenhao** [comment]
commit关闭时错误，手动关闭
